version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.9.0
    ports:
      - "9113:9113"
    restart: unless-stopped
    entrypoint: nginx-prometheus-exporter -nginx.scrape-uri=http://nginx/basic_status
    depends_on:
      - nginx
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
